### ISSUE TITLE
IMPROVE-INT ( Google cal and Sheet)

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/IMPROVE-INT#1]
<h3>IMPROVE-INT ( Google cal and Sheet)

**TASK OWNER:PUNI**

*DURATION: 2 DAYS*

Do the Google Ss template project. Below link has the specification.

https://docs.google.com/a/ssomens.com/document/d/1pmZJDqlW6dL02F2UEt50nA1LKpoomOz7B7Xr48xiNMg/edit

**Comment by punithavimalraj** [comment]
delivered
https://github.com/SSOMENSREPO/IMPROVE-INT/releases/tag/v1.0
