### ISSUE TITLE
IMPROVE INT  VIDEO

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/IMPROVE-INT#2]
PUNI,

CREATE DEMO VIDEO FOR IMPROVE INT. TARGET TODAY(24/04/2015)

WHILE TAKING DEMO GIVE PROPER TEXT.

**Comment by punithavimalraj** [comment]
delivered 

https://github.com/SSOMENSREPO/IMPROVE-INT/releases/tag/v2.0
