### ISSUE TITLE
IMPROVE INT CLIENT FEEDBACK

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/IMPROVE-INT#3]
TASK OWNER : PUNI

1.we do not need the form to add the task
2.we have an existing Google Sheet (with tasks in it and we simply copy the whole sheet, rather than adding tasks through the form every time)
3.all the dates in this Google Sheet (and all subsequent copies of this template) need to be added to Google Cal
4.We are going to use different Google Sheets

**Comment by punithavimalraj** [comment]
delivered

https://github.com/SSOMENSREPO/IMPROVE-INT/releases/tag/v3.0
